package mysql // import "gopkg.in/webnice/d2s.v1/d2s/mysql"

//import "gopkg.in/webnice/debug.v1"
//import "gopkg.in/webnice/log.v2"
//import ()

const (
	dbBoolean    = "boolean"
	dbBool       = "bool"
	dbTinyint    = "tinyint"
	dbInt        = "int"
	dbSmallint   = "smallint"
	dbMediumint  = "mediumint"
	dbBigint     = "bigint"
	dbChar       = "char"
	dbEnum       = "enum"
	dbVarchar    = "varchar"
	dbLongtext   = "longtext"
	dbMediumtext = "mediumtext"
	dbText       = "text"
	dbTinytext   = "tinytext"
	dbDate       = "date"
	dbDatetime   = "datetime"
	dbTime       = "time"
	dbTimestamp  = "timestamp"
	dbDecimal    = "decimal"
	dbDouble     = "double"
	dbFloat      = "float"
	dbBinary     = "binary"
	dbBlob       = "blob"
	dbLongblob   = "longblob"
	dbMediumblob = "mediumblob"
	dbVarbinary  = "varbinary"
	dbTinyblob   = "tinyblob"
)
