language: go

install:
  - go get github.com/mattn/goveralls
  - go get github.com/webnice/d2s

script:
  - make test
  - GOPATH=`pwd` GO111MODULE="off" $HOME/gopath/bin/goveralls -coverprofile=coverage.log -service=travis-ci -repotoken $COVERALLS_TOKEN

go:
  - "1.8.x"
  - "1.9.x"
  - "1.10.x"
  - "1.11.x"
  - "1.12.x"
  - master
