// Package d2s
package d2s

import (
	"text/template"
	"time"
)

var tpl = template.Must( // nolint: gochecknoglobals
	template.New("").
		Parse(`// nolint: lll

// НЕ РЕДАКТИРОВАТЬ! Изменения будут перезаписаны при следующей генерации.
// Code generated by running "go generate" by utility db2struct: "https://github.com/webnice/d2s"; DO NOT EDIT.
// Generator: db2struct (go install github.com/webnice/d2s/db2struct@latest)

// Структура создана автоматически на основе структуры таблицы базы данных.
// Название таблицы: "{{ .Table }}"

// Package {{ .Package }}
package {{ .Package }}

{{ if or .IsImportNil .IsImportTime }}
{{- if and .IsImportNil .IsImportTime }}import (
	"time"

	nul "gopkg.in/webnice/lin.v1/nl"
){{ end -}}
{{- if and .IsImportNil (not .IsImportTime) }}import nul "gopkg.in/webnice/lin.v1/nl"{{ end }}
{{- if and .IsImportTime (not .IsImportNil) }}import "time"{{ end }}
{{ end -}}
{{- $cf := .ColumnsFormat }}
// {{ .Struct }} {{ .Comment }}
type {{ .Struct }} struct {
{{- range .Columns }}
	{{ printf $cf .Name .Type .Tags .Comment }}
{{- end }}
}
`))

type tplVar struct {
	Timestamp        time.Time
	Database         string
	Table            string
	Package          string
	Struct           string
	Comment          string
	Columns          []*tplVarCol
	ColumnsFormat    string
	ColumnNameLength int
	ColumnTypeLength int
	ColumnTagsLength int
	IsImportNil      bool
	IsImportTime     bool
}

type tplVarCol struct {
	Name    string
	Type    string
	Tags    string
	Comment string
}
