// Package d2s
package d2s

import (
	"text/template"
	"time"
)

var tpl = template.Must( // nolint: gochecknoglobals
	template.New("").
		Parse(`// Code generated by running "go generate" by utility db2struct: "https://github.com/webnice/d2s"; DO NOT EDIT.
// Generator: db2struct (go get -u github.com/webnice/d2s/db2struct)

// The structure is based on the database table structure.
// Table: "{{ .Table }}"

package {{ .Package }}

{{- if or .IsImportNil .IsImportTime }}

import (
{{- if .IsImportTime }}
	"time"
{{- end }}
{{- if .IsImportNil }}
{{- if .IsImportTime }}
{{ end }}
	nul "gopkg.in/webnice/lin.v1/nl"{{ end }}
){{ end -}}
{{- $cf := .ColumnsFormat }}

// {{ .Struct }} {{ .Comment }}
type {{ .Struct }} struct {
{{- range .Columns }}
	{{ printf $cf .Name .Type .Tags .Comment }}
{{- end }}
}
`))

type tplVar struct {
	Timestamp        time.Time
	Database         string
	Table            string
	Package          string
	Struct           string
	Comment          string
	Columns          []*tplVarCol
	ColumnsFormat    string
	ColumnNameLength int
	ColumnTypeLength int
	ColumnTagsLength int
	IsImportNil      bool
	IsImportTime     bool
}

type tplVarCol struct {
	Name    string
	Type    string
	Tags    string
	Comment string
}
